nav:
- Aide en ligne: index.md
- "Nouveaut\xE9s": whatsnew/index.md
- '2019': whatsnew/2019/Whats_new_APrintStudio_2019.md
- '2018': whatsnew/2018/Whats_new_APrintStudio_2018.md
- '2017': whatsnew/2017/Whats_new_APrintStudio_2017.md
- Installation: installation/etapes.md
- "Installation, param\xE9trage": installation/installation.md
- "Description des fichiers install\xE9s": installation/description_folder.md
- Premiers Pas: documentation_utilisateur_welcome.md
- Ecouter un fichier Midi: 1-premiers-pas.md
- Piloter des instruments MIDI: 3-piloterinstrumentmidi.md
- Travailler avec les cartons: work_with_books.md
- Carton Virtuel: CartonVirtuel.md
- Modifier / Adjuster un carton: modify_book.md
- "Utiliser la s\xE9lection": modify_book_sel.md
- Exports vers Midi: 2-exportmidi.md
- Transformation visuelles (Model Editor): modeleditor/transformations_visuelles.md
- Prendre en main le model editor: modeleditor/introduction.md
- Ecrire son processeur: modeleditor/write_your_processor.md
- Documentation sur les processeurs: modeleditor/model_step_implementation.md
- "Num\xE9riser": numeriser.md
- Utiliser une WebCam: scan/use_webcam.md
- Construction d'un image du carton: scan/scanning_books_intro.md
- Reconnaissance d'une image de carton d'orgue: recognition/books.md
- "Cr\xE9er son mod\xE8le de ML": recognition/training.md
- Instruments et gammes: work_with_books.md
- "R\xE9cup\xE9rer des instruments existants": getinstruments.md
- Note sur l'enregistrement d'instruments: CreationInstrument.md
- "Machines sp\xE9ciales de perforation": perforation_cartons.md
- Comment perforer un carton: krunch/utilisation_perforatrice.md
- APrint Commander ou comment perforer sans PC: aprintcommander/index.md
- Concepts: concepts_introduction.md
- Gestion des instruments: repositories.md
- Carton Virtuel: CartonVirtuel.md
- "Etendre les fonctionnalit\xE9s": scripting.md
- Scripting: scripting/scripting.md
- Scripting Groovy: scripting/scripting_groovy.md
- Premiers pas avec le scripting: scripting/scripting_first_steps_quickscripts.md
- "Cr\xE9er une extension principale en script": scripting/extension_principale.md
- Scripts midi: scripting/scripting_midiscripts.md
- Note Helper: scripting/scripting_notehelper.md
- Scale Helper: scripting/scripting_scalehelper.md
- Transformer un carton: scripting/TransformerCarton.md
- "Creer une fen\xEAtre": scripting/scripting_gui.md
- "Scripting \xE9tendu avec Java": scripting/scripting_extended_using_java.md
- Developpement en Java: dev.md
- Choix dans le developpement du logiciel: Technology.md
- "D\xE9veloppement d'extensions": dev-extension.md
- "D\xE9veloppement d'extensions d'import / transformation de carton": dev-extension-import.md
- API Reference: referenceapi.md
plugins:
- search
#- pdf-export:
#    combined: true
site_name: APrint Documentation
theme:
  name: material
